version: '3.7'

services:
  api:
    build:
      context: .
    command: > 
      sh -c "python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
  db:
    image: postgres:13
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=post"
      - "POSTGRES_DB=postgres"

    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
networks:
    default:
        driver: bridge
        