# Generated by Django 4.1.3 on 2022-12-09 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z]{3}[-][0-9]{4}$', message='Plate number not allowed')])),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('left', models.BooleanField(default=True)),
            ],
        ),
    ]
